import { StoreProvider } from '@/src/shared/StoreProvider/StoreProvider'
import type { Metadata } from 'next'
import { Anton, Poppins } from 'next/font/google'

import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const anton = Anton({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-anton',
})

const poppins = Poppins({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-poppins',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${anton.variable} ${poppins.variable} antialiased font-poppins text-white`}>
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  )
}
