export const titles = [
  {
    slug: 'why-compliments-irritate',
    title: 'Why compliments sometimes irritate - and how to praise ethically',
    level: 'Beginner',
    image: '/coursesFor1.png',
    author: 'Dr. Jon Doe',
    date: 'September 1, 2025',
  },
  {
    slug: 'emotional-vocabulary-for-men',
    title: 'An emotional vocabulary for men',
    image: '/coursesFor2.png',
    level: 'Advanced',
    author: 'Dr. Jon Doe',
    date: 'September 1, 2025',
  },
  {
    slug: 'first-date-plan',
    title: 'First date plan without awkwardness',
    image: '/coursesFor3.png',
    level: 'For singles',
    author: 'Dr. Jon Doe',
    date: 'September 1, 2025',
  },

  {
    slug: 'boundaries-consent',
    title: 'Boundaries & consent: how to ask and hear the answer',
    image: '/coursesFor2.png',
    level: 'Advanced',
    author: 'Dr. Jon Doe',
    date: 'September 1, 2025',
  },
  {
    slug: 'hard-talk',
    title: 'Hard talks without fights',
    image: '/coursesFor1.png',
    level: 'Beginner',
    author: 'Dr. Jon Doe',
    date: 'September 1, 2025',
  },
  {
    slug: 'online-dating',
    title: 'Online dating without manipulation',
    image: '/coursesFor3.png',
    level: 'For singles',
    author: 'Dr. Jon Doe',
    date: 'September 1, 2025',
  },

  {
    slug: 'body-language',
    title: 'Body language that doesn’t mean consent',
    image: '/coursesFor1.png',
    level: 'Advanced',
    author: 'Dr. Jon Doe',
    date: 'September 1, 2025',
  },
  {
    slug: '10-minutes',
    title: '10‑minute de‑escalation',
    image: '/coursesFor2.png',
    level: 'Advanced',
    author: 'Dr. Jon Doe',
    date: 'September 1, 2025',
  },
  {
    slug: 'apology-works',
    title: 'The apology that actually works',
    image: '/coursesFor3.png',
    level: 'Advanced',
    author: 'Dr. Jon Doe',
    date: 'September 1, 2025',
  },

  {
    slug: 'boundaries-consent',
    title: 'Boundaries & consent: how to ask and hear the answer',
    image: '/coursesFor2.png',
    level: 'Advanced',
    author: 'Dr. Jon Doe',
    date: 'September 1, 2025',
  },
  {
    slug: 'hard-talk',
    title: 'Hard talks without fights',
    image: '/coursesFor1.png',
    level: 'Beginner',
    author: 'Dr. Jon Doe',
    date: 'September 1, 2025',
  },
  {
    slug: 'online-dating',
    title: 'Online dating without manipulation',
    image: '/coursesFor3.png',
    level: 'For singles',
    author: 'Dr. Jon Doe',
    date: 'September 1, 2025',
  },
]
